version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency_exchange_app
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      NODE_PORT: 7000
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/currency_exchange_db
      JWT_SECRET: super_secret_key_for_test
      JWT_EXPIRATION_TIME: 3600
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USER: tu_email@gmail.com
      MAIL_PASS: tu_password
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: currency_exchange_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: currency_exchange_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: