version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency_exchange_app
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      NODE_PORT: 7000
      NODE_ENV: production
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: currency_exchange_db
      MONGO_USERNAME: admin
      MONGO_PASSWORD: secret123      
      JWT_SECRET: super_secret_key_for_test
      JWT_EXPIRATION_TIME: 900000
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: tu_email@gmail.com
      EMAIL_PASSWORD: tu_password
      EMAIL_FROM: "Casa de Cambio Digital"
      RATES_URL: https://api.test.cambioseguro.com/api/v1.1/config/rates
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: currency_exchange_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
      MONGO_INITDB_DATABASE: currency_exchange_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: